name: sixam_mart
description: A Multi-vendor Food. Grocery, eCommerce, Pharmacy & Parcel service.
publish_to: 'none'
version: 1.0.1+103

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  carousel_slider: ^4.0.0
  connectivity: ^3.0.6
  country_code_picker: ^3.0.0
  dotted_border: ^2.0.0+1
  expandable_bottom_sheet: ^1.1.1+1
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  flutter_animarker: ^3.2.0
  flutter_facebook_auth: ^6.0.4
  flutter_html: ^3.0.0-alpha.5
  flutter_inappwebview: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_typeahead: ^4.3.7
  flutter_widget_from_html: ^0.8.5
  fwfh_selectable_text: ^0.8.3+1
  fwfh_text_style: ^2.22.8+1
  geolocator: ^12.0.0
  get: ^4.6.5
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.1.5
  google_maps_flutter_web: ^0.5.7
  google_sign_in: ^5.4.2
  google_sign_in_web: ^0.10.2
  http: ^1.2.1
  image_compression_flutter: ^1.0.3
  image_picker: ^1.1.1
  image_picker_ios: ^0.8.5+6
  intl: ^0.19.0
  path_provider: ^2.0.8
  phone_number: ^2.1.0
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  pointer_interceptor: ^0.10.1+1
  share_plus: ^9.0.0
  shared_preferences: ^2.0.11
  shimmer_animation: ^2.1.0+1
  sign_in_with_apple: ^6.1.0
  universal_html: ^2.0.8
  url_launcher: ^6.1.2
  url_strategy: ^0.2.0

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/image/logo.jpg"
    background_color: "#ffffff"
    theme_color: "#9618b9"

dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/font/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/font/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/font/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/font/Tajawal-Black.ttf
          weight: 900
